var superHeroName = "Batman";
var name = "Bruce Wayne";
var fly = false;
var hasBatmobile = true;
var life = 99;
var freeTime= null;
console.log('superHeroName', superHeroName, typeof(superHeroName));
console.log("name", name, typeof(name));
console.log('fly', fly, typeof(fly));
console.log('hasBatmobile',hasBatmobile, typeof(hasBatmobile));
console.log('life', life, typeof(life));
console.log('freeTime', freeTime, typeof(freeTime));