var first_name = 'Mandy'; 
var last_name = 'Zhang';
var age =34;
var address = "2790 E 27th AVE";
var dateOfBirth = "02/05/1986";
console.log(first_name);
console.log(last_name);
console.log(age);
console.log(address);
console.log(dateOfBirth);